window.PERIODIC_ELEMENTS = [
  {z:1,s:'H',n:'수소',mass:1.008,p:1,g:1,cat:'nonmetal',state:'기체',trait:'가장 가볍고 우주에서 가장 많습니다. 산소와 만나 물(H₂O)이 되고, 연료로도 씁니다.'},
  {z:2,s:'He',n:'헬륨',mass:4.003,p:1,g:18,cat:'noble',state:'기체',trait:'반응을 거의 하지 않는 비활성 기체입니다. 공기보다 가벼워 풍선에 넣습니다.'},
  {z:3,s:'Li',n:'리튬',mass:6.94,p:2,g:1,cat:'alkali',state:'고체',trait:'가장 가벼운 금속입니다. 물에 닿으면 반응하고, 충전 배터리에 많이 씁니다.'},
  {z:4,s:'Be',n:'베릴륨',mass:9.012,p:2,g:2,cat:'alkaline',state:'고체',trait:'가볍고 단단합니다. 가루·증기는 유독해서 실험실에서 주의합니다.'},
  {z:5,s:'B',n:'붕소',mass:10.81,p:2,g:13,cat:'metalloid',state:'고체',trait:'금속과 비금속의 중간 성질입니다. 유리·세제, 붕산에 들어 있습니다.'},
  {z:6,s:'C',n:'탄소',mass:12.011,p:2,g:14,cat:'nonmetal',state:'고체',trait:'생명체의 기본 원소입니다. 흑연·다이아몬드·석탄처럼 모습이 다양합니다.'},
  {z:7,s:'N',n:'질소',mass:14.007,p:2,g:15,cat:'nonmetal',state:'기체',trait:'공기 부피의 약 78%입니다. 잘 반응하지 않아 과자 봉지를 부풀리는 데 씁니다.'},
  {z:8,s:'O',n:'산소',mass:15.999,p:2,g:16,cat:'nonmetal',state:'기체',trait:'호흡과 연소에 꼭 필요합니다. 공기 부피의 약 21%이고, 물에 조금 녹습니다.'},
  {z:9,s:'F',n:'플루오린',mass:18.998,p:2,g:17,cat:'halogen',state:'기체',trait:'반응성이 가장 큰 원소 중 하나입니다. 치약의 플루오린 화합물이 이를 보호합니다.'},
  {z:10,s:'Ne',n:'네온',mass:20.18,p:2,g:18,cat:'noble',state:'기체',trait:'거의 반응하지 않습니다. 방전하면 붉은 주황빛이라 간판에 씁니다.'},
  {z:11,s:'Na',n:'나트륨',mass:22.99,p:3,g:1,cat:'alkali',state:'고체',trait:'은백색 금속으로 물에 격렬히 반응합니다. 소금(NaCl)의 성분입니다.'},
  {z:12,s:'Mg',n:'마그네슘',mass:24.305,p:3,g:2,cat:'alkaline',state:'고체',trait:'가볍고 불이 잘 붙습니다. 엽록소에도 들어 있고, 합금·불꽃에 씁니다.'},
  {z:13,s:'Al',n:'알루미늄',mass:26.982,p:3,g:13,cat:'post',state:'고체',trait:'가볍고 표면에 산화막이 생겨 잘 변하지 않습니다. 캔·창문 틀에 쓰이며 밀도는 철의 약 1/3입니다.'},
  {z:14,s:'Si',n:'규소',mass:28.085,p:3,g:14,cat:'metalloid',state:'고체',trait:'지각에 두 번째로 많습니다. 모래(SiO₂)와 반도체 칩의 핵심입니다.'},
  {z:15,s:'P',n:'인',mass:30.974,p:3,g:15,cat:'nonmetal',state:'고체',trait:'뼈·DNA에 들어 있습니다. 흰 인은 불이 잘 붙고 유독합니다.'},
  {z:16,s:'S',n:'황',mass:32.06,p:3,g:16,cat:'nonmetal',state:'고체',trait:'노란 고체입니다. 화산·온천에서 보이고, 황산·성냥에 쓰입니다.'},
  {z:17,s:'Cl',n:'염소',mass:35.45,p:3,g:17,cat:'halogen',state:'기체',trait:'자극적인 연두색 기체입니다. 소금·락스·수돗물 소독에 쓰입니다.'},
  {z:18,s:'Ar',n:'아르곤',mass:39.95,p:3,g:18,cat:'noble',state:'기체',trait:'공기 중 세 번째로 많습니다. 전구·용접처럼 반응을 막고 싶을 때 씁니다.'},
  {z:19,s:'K',n:'칼륨',mass:39.098,p:4,g:1,cat:'alkali',state:'고체',trait:'나트륨과 비슷하게 물에 잘 반응합니다. 바나나 등 세포 활동에 필요합니다.'},
  {z:20,s:'Ca',n:'칼슘',mass:40.078,p:4,g:2,cat:'alkaline',state:'고체',trait:'뼈와 이, 석회암·대리석(CaCO₃)의 성분입니다. 물에 약간 반응합니다.'},
  {z:21,s:'Sc',n:'스칸듐',mass:44.956,p:4,g:3,cat:'transition',state:'고체',trait:'가벼운 전이 금속입니다. 항공 합금처럼 특별한 재료에 조금 섞습니다.'},
  {z:22,s:'Ti',n:'타이타늄',mass:47.867,p:4,g:4,cat:'transition',state:'고체',trait:'가볍고 매우 단단하며 잘 변하지 않습니다. 인공 관절·비행기에 씁니다.'},
  {z:23,s:'V',n:'바나듐',mass:50.942,p:4,g:5,cat:'transition',state:'고체',trait:'강철을 더 질기게 만듭니다. 공구·스프링 강에 들어 있습니다.'},
  {z:24,s:'Cr',n:'크로뮴',mass:51.996,p:4,g:6,cat:'transition',state:'고체',trait:'광택이 나고 녹을 막습니다. 스테인리스강과 도금에 쓰입니다.'},
  {z:25,s:'Mn',n:'망가니즈',mass:54.938,p:4,g:7,cat:'transition',state:'고체',trait:'강철을 단단하게 합니다. 건전지와 지구의 암석에도 많습니다.'},
  {z:26,s:'Fe',n:'철',mass:55.845,p:4,g:8,cat:'transition',state:'고체',trait:'자석에 붙는 대표적인 금속입니다. 혈액의 헤모글로빈에도 들어 있습니다.'},
  {z:27,s:'Co',n:'코발트',mass:58.933,p:4,g:9,cat:'transition',state:'고체',trait:'자석 재료입니다. 파란색 물감·리튬 이온 배터리에도 쓰입니다.'},
  {z:28,s:'Ni',n:'니켈',mass:58.693,p:4,g:10,cat:'transition',state:'고체',trait:'광택이 나고 녹에 강합니다. 동전·스테인리스강에 들어 있습니다.'},
  {z:29,s:'Cu',n:'구리',mass:63.546,p:4,g:11,cat:'transition',state:'고체',trait:'전기와 열을 잘 통합니다. 전선·배관, 청동·황동의 성분입니다.'},
  {z:30,s:'Zn',n:'아연',mass:65.38,p:4,g:12,cat:'transition',state:'고체',trait:'철에 입혀 녹을 막습니다(도금). 산과 반응해 수소를 발생시킵니다.'},
  {z:31,s:'Ga',n:'갈륨',mass:69.723,p:4,g:13,cat:'post',state:'고체',trait:'손바닥 온도(약 30℃)에서 녹습니다. LED·반도체에 쓰입니다.'},
  {z:32,s:'Ge',n:'저마늄',mass:72.63,p:4,g:14,cat:'metalloid',state:'고체',trait:'초기의 반도체 재료입니다. 지금은 광통신·특수 렌즈에 씁니다.'},
  {z:33,s:'As',n:'비소',mass:74.922,p:4,g:15,cat:'metalloid',state:'고체',trait:'화합물이 유독하기로 유명합니다. 일부 반도체에도 쓰입니다.'},
  {z:34,s:'Se',n:'셀레늄',mass:78.971,p:4,g:16,cat:'nonmetal',state:'고체',trait:'빛에 따라 전기 성질이 바뀝니다. 복사기·영양소(아주 소량)로 쓰입니다.'},
  {z:35,s:'Br',n:'브로민',mass:79.904,p:4,g:17,cat:'halogen',state:'액체',trait:'실온에서 액체인 몇 안 되는 원소입니다. 적갈색이고 증기가 자극적입니다.'},
  {z:36,s:'Kr',n:'크립톤',mass:83.798,p:4,g:18,cat:'noble',state:'기체',trait:'비활성 기체입니다. 특수 조명·레이저에 쓰입니다.'},
  {z:37,s:'Rb',n:'루비듐',mass:85.468,p:5,g:1,cat:'alkali',state:'고체',trait:'반응성이 매우 큽니다. 원자시계 연구에 쓰입니다.'},
  {z:38,s:'Sr',n:'스트론튬',mass:87.62,p:5,g:2,cat:'alkaline',state:'고체',trait:'불꽃 반응에서 붉은색입니다. 불꽃놀이와 뼈 검사 시약에 쓰입니다.'},
  {z:39,s:'Y',n:'이트륨',mass:88.906,p:5,g:3,cat:'transition',state:'고체',trait:'LED·초전도 재료에 쓰이는 전이 금속입니다.'},
  {z:40,s:'Zr',n:'지르코늄',mass:91.224,p:5,g:4,cat:'transition',state:'고체',trait:'열과 부식에 강합니다. 원자로 피복관·세라믹에 쓰입니다.'},
  {z:41,s:'Nb',n:'나이오븀',mass:92.906,p:5,g:5,cat:'transition',state:'고체',trait:'초전도 자석과 특수 강철에 넣습니다.'},
  {z:42,s:'Mo',n:'몰리브데넘',mass:95.95,p:5,g:6,cat:'transition',state:'고체',trait:'녹는점이 높습니다. 공구 강·효소에도 소량 들어 있습니다.'},
  {z:43,s:'Tc',n:'테크네튬',mass:98,p:5,g:7,cat:'transition',state:'고체',trait:'자연에 거의 없는 방사성 원소입니다. 병원 영상 검사에 씁니다.'},
  {z:44,s:'Ru',n:'루테늄',mass:101.07,p:5,g:8,cat:'transition',state:'고체',trait:'백금족 금속입니다. 전자기기와 촉매에 쓰입니다.'},
  {z:45,s:'Rh',n:'로듐',mass:102.91,p:5,g:9,cat:'transition',state:'고체',trait:'반사율이 큽니다. 자동차 촉매 변환 장치·도금에 쓰입니다.'},
  {z:46,s:'Pd',n:'팔라듐',mass:106.42,p:5,g:10,cat:'transition',state:'고체',trait:'수소를 잘 흡수합니다. 촉매와 치과 재료에 쓰입니다.'},
  {z:47,s:'Ag',n:'은',mass:107.87,p:5,g:11,cat:'transition',state:'고체',trait:'전기·열 전도도가 가장 큰 금속입니다. 장신구·사진·살균에도 쓰입니다.'},
  {z:48,s:'Cd',n:'카드뮴',mass:112.41,p:5,g:12,cat:'transition',state:'고체',trait:'배터리에 쓰였지만 유독합니다. 환경·건강에 주의가 필요합니다.'},
  {z:49,s:'In',n:'인듐',mass:114.82,p:5,g:13,cat:'post',state:'고체',trait:'잘 늘어나는 무른 금속입니다. 터치스크린 투명 전극에 쓰입니다.'},
  {z:50,s:'Sn',n:'주석',mass:118.71,p:5,g:14,cat:'post',state:'고체',trait:'철에 입혀 양철을 만듭니다. 땜납·청동의 성분입니다.'},
  {z:51,s:'Sb',n:'안티모니',mass:121.76,p:5,g:15,cat:'metalloid',state:'고체',trait:'합금에 넣으면 단단해집니다. 배터리 극판·난연제에 쓰입니다.'},
  {z:52,s:'Te',n:'텔루륨',mass:127.6,p:5,g:16,cat:'metalloid',state:'고체',trait:'반도체·태양 전지 재료입니다. 희귀하고 화합물은 냄새가 셉니다.'},
  {z:53,s:'I',n:'아이오딘',mass:126.9,p:5,g:17,cat:'halogen',state:'고체',trait:'보라색으로 승화합니다. 소독약과 갑상샘 호르몬에 필요합니다.'},
  {z:54,s:'Xe',n:'제논',mass:131.29,p:5,g:18,cat:'noble',state:'기체',trait:'비활성 기체입니다. 카메라 플래시·마취·이온 엔진에 쓰입니다.'},
  {z:55,s:'Cs',n:'세슘',mass:132.91,p:6,g:1,cat:'alkali',state:'고체',trait:'녹는점이 낮고 반응성이 큽니다. 원자시계의 기준 원소입니다.'},
  {z:56,s:'Ba',n:'바륨',mass:137.33,p:6,g:2,cat:'alkaline',state:'고체',trait:'불꽃 반응에서 초록색입니다. 위장 엑스선 조영제(황산 바륨)에 씁니다.'},
  {z:57,s:'La',n:'란타넘',mass:138.91,p:6,g:3,cat:'lanthanide',state:'고체',trait:'란타넘족의 첫 원소입니다. 카메라 렌즈 유리·합금에 쓰입니다.'},
  {z:58,s:'Ce',n:'세륨',mass:140.12,p:6,g:4,cat:'lanthanide',state:'고체',trait:'가장 흔한 희토류입니다. 라이터 돌·유리 연마에 쓰입니다.'},
  {z:59,s:'Pr',n:'프라세오디뮴',mass:140.91,p:6,g:5,cat:'lanthanide',state:'고체',trait:'노란 유리·강한 자석 합금에 쓰이는 희토류입니다.'},
  {z:60,s:'Nd',n:'네오디뮴',mass:144.24,p:6,g:6,cat:'lanthanide',state:'고체',trait:'매우 강한 자석을 만듭니다. 이어폰·모터에 들어 있습니다.'},
  {z:61,s:'Pm',n:'프로메튬',mass:145,p:6,g:7,cat:'lanthanide',state:'고체',trait:'방사성 희토류입니다. 자연에 거의 없고 특수 전지에 쓰입니다.'},
  {z:62,s:'Sm',n:'사마륨',mass:150.36,p:6,g:8,cat:'lanthanide',state:'고체',trait:'고온에서도 자성이 유지되는 자석 재료입니다.'},
  {z:63,s:'Eu',n:'유로퓸',mass:151.96,p:6,g:9,cat:'lanthanide',state:'고체',trait:'형광 물질로 유명합니다. 유로화 지폐 감식·TV 형광체에 쓰입니다.'},
  {z:64,s:'Gd',n:'가돌리늄',mass:157.25,p:6,g:10,cat:'lanthanide',state:'고체',trait:'자기공명영상(MRI) 조영제와 중성자 흡수에 쓰입니다.'},
  {z:65,s:'Tb',n:'터븀',mass:158.93,p:6,g:11,cat:'lanthanide',state:'고체',trait:'초록 형광과 특수 자석에 쓰이는 희토류입니다.'},
  {z:66,s:'Dy',n:'디스프로슘',mass:162.5,p:6,g:12,cat:'lanthanide',state:'고체',trait:'네오디뮴 자석을 고온에서 더 강하게 만드는 데 넣습니다.'},
  {z:67,s:'Ho',n:'홀뮴',mass:164.93,p:6,g:13,cat:'lanthanide',state:'고체',trait:'자기 성질이 큽니다. 레이저·특수 자석에 쓰입니다.'},
  {z:68,s:'Er',n:'어븀',mass:167.26,p:6,g:14,cat:'lanthanide',state:'고체',trait:'광섬유 증폭기와 분홍 유리에 쓰입니다.'},
  {z:69,s:'Tm',n:'툴륨',mass:168.93,p:6,g:15,cat:'lanthanide',state:'고체',trait:'매우 드문 희토류입니다. 휴대용 엑스선 장치에 쓰입니다.'},
  {z:70,s:'Yb',n:'이터븀',mass:173.05,p:6,g:16,cat:'lanthanide',state:'고체',trait:'스테인리스 개량과 원자시계·레이저에 쓰입니다.'},
  {z:71,s:'Lu',n:'루테튬',mass:174.97,p:6,g:17,cat:'lanthanide',state:'고체',trait:'란타넘족의 마지막입니다. 석유 촉매·PET 스캐너에 쓰입니다.'},
  {z:72,s:'Hf',n:'하프늄',mass:178.49,p:6,g:4,cat:'transition',state:'고체',trait:'지르코늄과 닮았습니다. 원자로 제어봉에 쓰입니다.'},
  {z:73,s:'Ta',n:'탄탈럼',mass:180.95,p:6,g:5,cat:'transition',state:'고체',trait:'산에도 잘 견딥니다. 휴대폰 커패시터·의료 임플란트에 쓰입니다.'},
  {z:74,s:'W',n:'텅스텐',mass:183.84,p:6,g:6,cat:'transition',state:'고체',trait:'녹는점이 금속 중 매우 높습니다. 전구 필라멘트·공구에 씁니다.'},
  {z:75,s:'Re',n:'레늄',mass:186.21,p:6,g:7,cat:'transition',state:'고체',trait:'매우 드문 금속입니다. 제트 엔진 합금·촉매에 쓰입니다.'},
  {z:76,s:'Os',n:'오스뮴',mass:190.23,p:6,g:8,cat:'transition',state:'고체',trait:'밀도가 가장 큰 원소입니다. 단단한 합금에 조금 섞습니다.'},
  {z:77,s:'Ir',n:'이리듐',mass:192.22,p:6,g:9,cat:'transition',state:'고체',trait:'부식에 매우 강합니다. 점화 플러그·표준 질량 원기에 쓰였습니다.'},
  {z:78,s:'Pt',n:'백금',mass:195.08,p:6,g:10,cat:'transition',state:'고체',trait:'잘 변하지 않는 귀금속입니다. 촉매 변환 장치·장신구에 쓰입니다.'},
  {z:79,s:'Au',n:'금',mass:196.97,p:6,g:11,cat:'transition',state:'고체',trait:'녹슬지 않고 잘 늘어납니다. 밀도 19.3 g/cm³로 아주 무겁습니다.'},
  {z:80,s:'Hg',n:'수은',mass:200.59,p:6,g:12,cat:'transition',state:'액체',trait:'실온에서 액체인 금속입니다. 증기가 유독해 온도계에서 거의 빠졌습니다.'},
  {z:81,s:'Tl',n:'탈륨',mass:204.38,p:6,g:13,cat:'post',state:'고체',trait:'무른 금속이고 화합물이 매우 유독합니다.'},
  {z:82,s:'Pb',n:'납',mass:207.2,p:6,g:14,cat:'post',state:'고체',trait:'무겁고 방사선 차폐에 씁니다. 예전 페인트·파이프는 중독 위험이 있습니다.'},
  {z:83,s:'Bi',n:'비스무트',mass:208.98,p:6,g:15,cat:'post',state:'고체',trait:'독성이 비교적 작은 중금속입니다. 위장약·저융점 합금에 쓰입니다.'},
  {z:84,s:'Po',n:'폴로늄',mass:209,p:6,g:16,cat:'post',state:'고체',trait:'강한 방사성 원소입니다. 자연에 아주 적고 위험합니다.'},
  {z:85,s:'At',n:'아스타틴',mass:210,p:6,g:17,cat:'halogen',state:'고체',trait:'가장 드문 할로젠입니다. 방사성이 강해 연구가 어렵습니다.'},
  {z:86,s:'Rn',n:'라돈',mass:222,p:6,g:18,cat:'noble',state:'기체',trait:'방사성 비활성 기체입니다. 지하실 공기 관리가 중요합니다.'},
  {z:87,s:'Fr',n:'프랑슘',mass:223,p:7,g:1,cat:'alkali',state:'고체',trait:'가장 반응성이 큰 금속으로 추정됩니다. 방사성으로 양이 거의 없습니다.'},
  {z:88,s:'Ra',n:'라듐',mass:226,p:7,g:2,cat:'alkaline',state:'고체',trait:'퀴리 부부가 발견했습니다. 강한 방사성 원소입니다.'},
  {z:89,s:'Ac',n:'악티늄',mass:227,p:7,g:3,cat:'actinide',state:'고체',trait:'악티늄족의 첫 원소입니다. 방사성이 강합니다.'},
  {z:90,s:'Th',n:'토륨',mass:232.04,p:7,g:4,cat:'actinide',state:'고체',trait:'핵연료 연구에 쓰입니다. 방사성 원소입니다.'},
  {z:91,s:'Pa',n:'프로트악티늄',mass:231.04,p:7,g:5,cat:'actinide',state:'고체',trait:'우라늄 붕괴 과정에서 나옵니다. 희귀하고 방사성입니다.'},
  {z:92,s:'U',n:'우라늄',mass:238.03,p:7,g:6,cat:'actinide',state:'고체',trait:'핵연료와 원자력의 핵심입니다. 방사성 중금속입니다.'},
  {z:93,s:'Np',n:'넵투늄',mass:237,p:7,g:7,cat:'actinide',state:'고체',trait:'원자로에서 생기는 인공 악티늄족입니다.'},
  {z:94,s:'Pu',n:'플루토늄',mass:244,p:7,g:8,cat:'actinide',state:'고체',trait:'핵무기·일부 원자로 연료로 쓰입니다. 매우 위험합니다.'},
  {z:95,s:'Am',n:'아메리슘',mass:243,p:7,g:9,cat:'actinide',state:'고체',trait:'화재 경보기(이온식)에 아주 소량 쓰입니다.'},
  {z:96,s:'Cm',n:'퀴륨',mass:247,p:7,g:10,cat:'actinide',state:'고체',trait:'퀴리의 이름을 딴 인공 방사성 원소입니다.'},
  {z:97,s:'Bk',n:'버클륨',mass:247,p:7,g:11,cat:'actinide',state:'고체',trait:'버클리에서 만든 인공 원소입니다. 연구용입니다.'},
  {z:98,s:'Cf',n:'캘리포늄',mass:251,p:7,g:12,cat:'actinide',state:'고체',trait:'중성자 선원으로 쓰입니다. 강력히 방사성입니다.'},
  {z:99,s:'Es',n:'아인슈타이늄',mass:252,p:7,g:13,cat:'actinide',state:'고체',trait:'아인슈타인의 이름을 딴 인공 원소입니다.'},
  {z:100,s:'Fm',n:'페르뮴',mass:257,p:7,g:14,cat:'actinide',state:'고체',trait:'페르미의 이름을 딴 인공 원소입니다. 수명이 짧습니다.'},
  {z:101,s:'Md',n:'멘델레븀',mass:258,p:7,g:15,cat:'actinide',state:'고체',trait:'멘델레예프의 이름을 딴 인공 원소입니다.'},
  {z:102,s:'No',n:'노벨륨',mass:259,p:7,g:16,cat:'actinide',state:'고체',trait:'노벨의 이름을 딴 인공 원소입니다. 아주 조금밖에 만들지 못합니다.'},
  {z:103,s:'Lr',n:'로렌슘',mass:266,p:7,g:17,cat:'actinide',state:'고체',trait:'악티늄족의 마지막입니다. 로런스의 이름을 땄습니다.'},
  {z:104,s:'Rf',n:'러더포듐',mass:267,p:7,g:4,cat:'transition',state:'고체',trait:'인공 초중원소입니다. 원자가 금방 붕괴합니다.'},
  {z:105,s:'Db',n:'더브늄',mass:268,p:7,g:5,cat:'transition',state:'고체',trait:'인공 초중원소입니다. 수명이 매우 짧습니다.'},
  {z:106,s:'Sg',n:'시보귬',mass:269,p:7,g:6,cat:'transition',state:'고체',trait:'시보그의 이름을 딴 인공 원소입니다.'},
  {z:107,s:'Bh',n:'보륨',mass:270,p:7,g:7,cat:'transition',state:'고체',trait:'보어의 이름을 딴 인공 초중원소입니다.'},
  {z:108,s:'Hs',n:'하슘',mass:277,p:7,g:8,cat:'transition',state:'고체',trait:'독일 헤센(하슘)에서 이름을 딴 인공 원소입니다.'},
  {z:109,s:'Mt',n:'마이트너륨',mass:278,p:7,g:9,cat:'unknown',state:'고체',trait:'마이트너의 이름을 딴 인공 원소입니다. 성질은 거의 측정되지 않았습니다.'},
  {z:110,s:'Ds',n:'다름슈타튬',mass:281,p:7,g:10,cat:'unknown',state:'고체',trait:'다름슈타트에서 만든 인공 원소입니다.'},
  {z:111,s:'Rg',n:'뢴트게늄',mass:282,p:7,g:11,cat:'unknown',state:'고체',trait:'뢴트겐의 이름을 딴 인공 원소입니다.'},
  {z:112,s:'Cn',n:'코페르니슘',mass:285,p:7,g:12,cat:'transition',state:'고체',trait:'코페르니쿠스의 이름을 땄습니다. 금속성이 있을 것으로 봅니다.'},
  {z:113,s:'Nh',n:'니호늄',mass:286,p:7,g:13,cat:'unknown',state:'고체',trait:'일본에서 발견한 인공 원소입니다(니혼).'},
  {z:114,s:'Fl',n:'플레로븀',mass:289,p:7,g:14,cat:'unknown',state:'고체',trait:'플레로프 연구소의 이름을 딴 인공 원소입니다.'},
  {z:115,s:'Mc',n:'모스코븀',mass:290,p:7,g:15,cat:'unknown',state:'고체',trait:'모스크바의 이름을 딴 인공 원소입니다.'},
  {z:116,s:'Lv',n:'리버모륨',mass:293,p:7,g:16,cat:'unknown',state:'고체',trait:'리버모어 연구소의 이름을 딴 인공 원소입니다.'},
  {z:117,s:'Ts',n:'테네신',mass:294,p:7,g:17,cat:'unknown',state:'고체',trait:'테네시의 이름을 딴 할로젠 자리의 인공 원소입니다.'},
  {z:118,s:'Og',n:'오가네손',mass:294,p:7,g:18,cat:'unknown',state:'기체',trait:'오가네시안의 이름을 딴 18족 인공 원소입니다. 수명이 극히 짧습니다.'},
];
